export const ADD_USER_WAITING = 'ADD_USER_WAITING';
export const REMOVE_USER_WAITING = 'REMOVE_USER_WAITING';
export const ADD_NOT_PICKUP = 'ADD_NOT_PICKUP';
export const REMOVE_NOT_PICKUP = 'REMOVE_NOT_PICKUP';
export const ADD_PICKUP_RIDER = 'ADD_PICKUP_RIDER';
export const REMOVE_PICKUP_RIDER = 'REMOVE_PICKUP_RIDER';
export const ADD_COMPLETE_RIDER = 'ADD_COMPLETE_RIDER';
export const SHOW_DIRECTION = 'SHOW_DIRECTION';